# Generated by Django 4.0.3 on 2022-05-04 14:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Utilisateur', 'User'), ('Responsable', 'Responsable'), ('Admin', 'Admin'), ('Service', 'Service')], default=('Utilisateur', 'User'), max_length=30)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers are allowed')])),
                ('is_banned', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='user_img')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catégorie', models.CharField(choices=[('higène', 'Higène'), ('entretien', 'Entretien'), ('santé', 'Santé'), ('sécurité', 'Sécurité'), ('technique', 'Technique'), ('objet perdu', 'Objet perdu'), ('autre', 'Autre')], default='Autre', max_length=50)),
                ('lieu', models.CharField(max_length=50, null=True)),
                ('priorité', models.CharField(choices=[(1, 'Urgence'), (2, 'Etat critique'), (3, 'Etat normal')], default='Etat normal', max_length=30)),
                ('objet', models.TextField(null=True)),
                ('corps', models.TextField(null=True)),
                ('publiée', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiée', 'Publiée')], default='brouillon', max_length=10)),
                ('image', models.ImageField(null=True, upload_to='declaration_images/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publiée', '-priorité'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification.responsable+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification.service+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification.user+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MDeclarationRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='madrasaticApp.mdeclaration')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_rejections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationComplementDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_demands', to='madrasaticApp.mdeclaration')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_complement_demands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
