# Generated by Django 4.0.3 on 2022-05-04 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdeclaration',
            name='etat',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publiée', 'Publiée'), ('non traitée', 'non traitée'), ('en cours de traitement', 'en cours de traitement'), ('traitée', 'traitée')], default='brouillon', max_length=100),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mdeclaration',
            name='catégorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_categorie', to='madrasaticApp.category'),
        ),
    ]
