# Generated by Django 4.0.3 on 2022-05-05 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0002_alter_mdeclaration_etat_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdeclaration',
            name='parent_declaration',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declaration.parent_declaration+', to='madrasaticApp.mdeclaration'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='tel',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers are allowed')]),
        ),
    ]
