# Generated by Django 4.0.3 on 2022-03-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0002_myuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
