# Generated by Django 4.0.3 on 2022-04-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0003_remove_myuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='user_img'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Utilisateur', 'User'), ('Responsable', 'Responsable'), ('Admin', 'Admin'), ('Service', 'Service')], default=('Utilisateur', 'User'), max_length=30),
        ),
    ]
