# Generated by Django 4.0.3 on 2022-04-27 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0004_alter_myuser_img_alter_myuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('priority', models.CharField(choices=[(1, 'critical'), (2, 'important'), (3, 'normal'), (4, 'low')], default='normal', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('not_validated', 'not_validated'), ('lack_of_info', 'lack_of_info'), ('validated', 'validated'), ('refused', 'refused'), ('under_treatment', 'under_treatment'), ('treated', 'treated')], default='not_validated', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='declaration_images/', verbose_name='user_img')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user.declarations+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
