# Generated by Django 4.0.3 on 2022-05-04 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0004_alter_myuser_img_alter_myuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catégorie', models.CharField(choices=[('higène', 'Higène'), ('entretien', 'Entretien'), ('santé', 'Santé'), ('sécurité', 'Sécurité'), ('technique', 'Technique'), ('objet perdu', 'Objet perdu'), ('autre', 'Autre')], default='Autre', max_length=50)),
                ('lieu', models.CharField(max_length=50, null=True)),
                ('priorité', models.CharField(choices=[(1, 'Urgence'), (2, 'Etat critique'), (3, 'Etat normal')], default='Etat normal', max_length=30)),
                ('objet', models.TextField(null=True)),
                ('corps', models.TextField(null=True)),
                ('publiée', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiée', 'Publiée')], default='brouillon', max_length=10)),
                ('image', models.ImageField(null=True, upload_to='declaration_images/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publiée', '-priorité'),
            },
        ),
        migrations.CreateModel(
            name='MDeclarationRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='madrasaticApp.mdeclaration')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_rejections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationComplementDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_demands', to='madrasaticApp.mdeclaration')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_complement_demands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
