# Generated by Django 4.0.3 on 2022-05-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0004_alter_mdeclaration_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdeclaration',
            name='etat',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publiée', 'Publiée'), ('non traitée', 'non traitée'), ('en cours ', 'en cours'), ('traitée', 'traitée')], default='brouillon', max_length=150),
        ),
    ]
