# Generated by Django 4.0.3 on 2022-04-29 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0004_alter_myuser_img_alter_myuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('objet', models.TextField(null=True)),
                ('corps', models.TextField()),
                ('publiée', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiée', 'Publiée')], default='brouillon', max_length=10)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_Declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publiée',),
            },
        ),
        migrations.CreateModel(
            name='MDeclarationRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='madrasaticApp.mdeclaration')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_rejections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
