# Generated by Django 4.0.3 on 2022-04-29 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasaticApp', '0005_mdeclaration_mdeclarationrejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationComplementDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_demands', to='madrasaticApp.mdeclaration')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_complement_demands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
